version: '3.4'
services:
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
    command: [ 'redis-server', '--bind', 'redis', '--port', '6379' ]
    networks:
      - n1

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nestDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - n1

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9000:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
    networks:
      - n1

volumes:
  postgres:
  pgadmin:

networks:
  n1:
